name = "hello-go-go"
main = "src/index.js"
compatibility_date = "2026-01-20"

[limits]
cpu_ms = 300000

# Durable Object 绑定
[[durable_objects.bindings]]
name = "PROXY_DO"
class_name = "ProxyDurableObject"

